name: Publish GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      working-directory: Packages/PackageManagerTest
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
